### ISSUE TITLE
lifetimes

### ISSUE THREAD

**Issue by db-keli** [db-keli/kelvin#5]
Add lifetime annotations to functions declarations

**Comment by g4titanx** [comment]
can you give an example of a function that needs lifetime annotations?

**Comment by db-keli** [comment]
check_if_file_exists function and read_user_data function in data.rs

**Comment by g4titanx** [comment]
the check_if_file_exits and read_user_data function takes two &str arguments and does not return any references. rust can infer the lifetimes, so explicit lifetime annotations will make it redundant.

**Comment by db-keli** [comment]
Oh yeah,
but since codebase would get bigger I just thought annotations should be done now, to save it from complexity later on

**Comment by g4titanx** [comment]
right
